/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.FacultyWorkArea;

import Business.UniversitySystem;
import Business.UserAccounts.UserAccount;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import javax.swing.JOptionPane;
import UserInterface.MainLoginFrame;
import Business.*;


/**
 *
 * @author anusha
 */
public class FacultyDashboard extends javax.swing.JFrame {
    private UniversitySystem system;
    private UserAccount currentUser;
    private FacultyProfile facultyProfile;

    public FacultyDashboard(UniversitySystem system, UserAccount user) {
        initComponents();
        this.system = system;
        this.currentUser = user;
        this.facultyProfile = (FacultyProfile) user.getProfile();
        
        setTitle("Faculty Dashboard - " + facultyProfile.getPerson().getPersonId());
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageCourses = new javax.swing.JButton();
        btnGradeStudents = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        btnTuitionInsight = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Faculty Dashboard");

        btnManageCourses.setText("Manage Courses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnGradeStudents.setText("Grade Students");
        btnGradeStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeStudentsActionPerformed(evt);
            }
        });

        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        btnTuitionInsight.setText("Tuition Insight");
        btnTuitionInsight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionInsightActionPerformed(evt);
            }
        });

        btnMyProfile.setText("My Profile");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageCourses)
                            .addComponent(btnPerformanceReports))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTuitionInsight)
                            .addComponent(btnGradeStudents)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnLogout)
                                .addComponent(btnMyProfile)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGradeStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuitionInsight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    CourseManagementJPanel panel = new CourseManagementJPanel(system, facultyProfile);
    panel.setVisible(true);

        // TODO add your handling code here:
    }                                                

    private void btnGradeStudentsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
            GradeStudentsJPanel panel = new GradeStudentsJPanel(system, facultyProfile);
    panel.setVisible(true);


        // TODO add your handling code here:
    }                                                

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {                                                      
            PerformanceReportsJPanel panel = new PerformanceReportsJPanel(system, facultyProfile);
    panel.setVisible(true);

        // TODO add your handling code here:
    }                                                     

    private void btnTuitionInsightActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        TuitionInsightJPanel panel = new TuitionInsightJPanel(system, facultyProfile);
    panel.setVisible(true);

        // TODO add your handling code here:
    }                                                 

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
            int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        MainLoginFrame login = new MainLoginFrame();
        login.setVisible(true);
        this.dispose();
    }

        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Create test system with pre-populated data
                UniversitySystem testSystem = Business.ConfigureSystem.configure();
                
                // Get a faculty user account for testing
                // Index 11 = first faculty (after 1 admin + 10 students)
                UserAccount testUser = testSystem.getUserAccountDirectory().getAllAccounts().get(11);
                
                // Create dashboard with parameters
                new FacultyDashboard(testSystem, testUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGradeStudents;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnTuitionInsight;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration                   
}
